[workspace]
git_release_enable = false
dependencies_update = true
changelog_update = false

[[package]]
name = "hypertext"
changelog_update = true
changelog_include = [
  "hypertext-macros",
]
changelog_path = "./CHANGELOG.md"
git_release_enable = true

[changelog]
body = """

## [{{ version }}]{%- if release_link -%}({{ release_link }}){% endif %} - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{commit.scope}})* {% endif %}\
          {% if commit.breaking %}[**breaking**] {% endif %}\
          {{ commit.message }}\
          {% if commit.remote.pr_number %} (#{{ commit.remote.pr_number }}){% endif -%}
    {% endfor %}
{% endfor %}
"""
commit_parsers = [
  { message = "(?i)^.*(change|switch|swap).*$", group = "<!-- 1 -->Changed" },
  { message = "(?i)^.*deprecate.*$", group = "<!-- 2 -->Deprecated" },
  { message = "(?i)^.*(remove|delete).*$", group = "<!-- 3 -->Removed" },
  { message = "(?i)^.*security.*$", group = "<!-- 5 -->Security" },
  { message = '^feat(\(.*?\))?!?:.*$', group = "<!-- 0 -->Added" },
  { message = '^fix(\(.*?\))?!?:.*$', group = "<!-- 4 -->Fixed" },
  { message = ".*", group = "<!-- 6 -->Other" },
]